import { ProductFormCreate } from '@/components/work/product-form-create';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Work - DINCT',
  description: 'Generated by create next app',
};
const CreateWorkPage = () => {
  return (
    <>
      <ProductFormCreate />
    </>
  );
};

export default CreateWorkPage;
